# Generated by Django 2.2.7 on 2020-10-07 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('titleorigin', models.CharField(max_length=200, null=True)),
                ('nation', models.CharField(max_length=100, null=True)),
                ('releasedate', models.CharField(max_length=200, null=True)),
                ('director', models.CharField(max_length=100, null=True)),
                ('poster', models.TextField(null=True)),
                ('plot', models.TextField(null=True)),
                ('rate', models.CharField(max_length=100, null=True)),
                ('ratecnt', models.TextField(null=True)),
                ('rsum', models.FloatField(null=True)),
                ('ravg', models.FloatField(null=True)),
                ('rcnt', models.IntegerField(null=True)),
                ('actors', models.ManyToManyField(blank=True, to='movies.Actor')),
                ('genres', models.ManyToManyField(blank=True, to='movies.Genre')),
                ('keywords', models.ManyToManyField(blank=True, to='movies.Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.FloatField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
